core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'
# those are the links fore core app 
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

# links for all the project 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('project/', include('project.urls', namespace='project')),
    path('', include('core.urls', namespace='core')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
# those are the links for register app 
urlpatterns = [
    path('new-user/', views.register, name='new-user'),
    path('new-company/', views.newCompany, name='new-company'),
    path('users/', views.usersView, name='users'),
    path('users/profile', views.profile, name='profile'),
    path('users/', views.user_view, name='user'),
]

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)

# Create your models here.
# project object
class Project(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    assign = models.ManyToManyField(User)
    efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    dead_line = models.DateField()
    company = models.ForeignKey('register.Company', on_delete=models.CASCADE)
    complete_per = models.FloatField(max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)

    add_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)

# task object 
class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField(User)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

register/models.py
from django.db import models
from django.contrib.auth.models import User
from project.models import Project

# Create your models here.
# company object
class Company(models.Model):
    social_name = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    city = models.CharField(max_length=50)
    found_date = models.DateField()

    class Meta:
        verbose_name_plural = 'Companies'
        ordering = ('name',)


    def __str__(self):
        return (self.name)
# user object
class UserProfile(models.Model):
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    project = models.ManyToManyField(Project, blank=True)
    img    = models.ImageField(upload_to='media', blank=True, default='core/avatar/blank_profile.png')

    def __str__(self):
        return (str(self.user))

    

register/forms.py
from django import forms
from register.models import Company as Comp
from register.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# this is class is the form form register to create new user account
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='E-mail', required=True)
    company = forms.ModelChoiceField(queryset=Comp.objects.all())

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'company',
            'password1',
            'password2',
        }

        labels = {
            'first_name': 'Name',
            'last_name': 'Last Name',
            'company': 'Company',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        company = self.cleaned_data['company']

        if commit:
            user.save()
            user_profile = UserProfile.objects.create(user=user, company=Comp.objects.get(name=company))
            user_profile.save()

        return user

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Retype Password'
        self.fields['company'].widget.attrs['class'] = 'form-control'


class CompanyRegistrationForm(forms.Form):
    social_name = forms.CharField(max_length=80)
    name = forms.CharField(max_length=80)
    email = forms.EmailField()
    city = forms.CharField(max_length=50)
    found_date = forms.DateField()

    class Meta:
        model = Comp


    def save(self, commit=True):
        company = Comp()
        company.social_name = self.cleaned_data['social_name']
        company.name = self.cleaned_data['name']
        company.email = self.cleaned_data['email']
        company.city = self.cleaned_data['city']
        company.found_date = self.cleaned_data['found_date']

        if commit:
            company.save()


    def __init__(self, *args, **kwargs):
        super(CompanyRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['social_name'].widget.attrs['class'] = 'form-control'
        self.fields['social_name'].widget.attrs['placeholder'] = 'Social Name'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['city'].widget.attrs['class'] = 'form-control'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['found_date'].widget.attrs['class'] = 'form-control'
        self.fields['found_date'].widget.attrs['placeholder'] = 'Found date'

# this form form the picture of the user
class ProfilePictureForm(forms.Form):
    img = forms.ImageField()
    class Meta:
        model = UserProfile
        fields = ['img']

    def save(self, request, commit=True):
        user = request.user.userprofile_set.first()
        user.img = self.cleaned_data['img']

        if commit:
            user.save()

        return user

    def __init__(self, *args, **kwargs):
        super(ProfilePictureForm, self).__init__(*args, **kwargs)
        self.fields['img'].widget.attrs['class'] = 'custom-file-input'
        self.fields['img'].widget.attrs['id'] = 'validatedCustomFile'

register/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect
from project.models import Task
from .models import UserProfile
from .forms import RegistrationForm
from .forms import CompanyRegistrationForm
from .forms import ProfilePictureForm


# Create your views here.
# function for register new account
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            user = form.save()
            created = True
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            context = {'created' : created}
            return render(request, 'register/reg_form.html', context)
        else:
            return render(request, 'register/reg_form.html', context)
    else:
        form = RegistrationForm()
        context = {
            'form' : form,
        }
        return render(request, 'register/reg_form.html', context)

# function to see all users registered
def usersView(request):
    users = UserProfile.objects.all()
    tasks = Task.objects.all()
    context = {
        'users': users,
        'tasks': tasks,
    }
    return render(request, 'register/users.html', context)

def user_view(request):
    profile_id=request.GET.get('profile_id')
    user = UserProfile.objects.get(id=profile_id)
    context = {
        'user_view' : user,
    }
    return render(request, 'register/user.html', context)

# function to see your profile
def profile(request):
    if request.method == 'POST':
        img_form = ProfilePictureForm(request.POST, request.FILES)
        print('PRINT 1: ', img_form)
        context = {'img_form' : img_form }
        if img_form.is_valid():
            img_form.save(request)
            updated = True
            context = {'img_form' : img_form, 'updated' : updated }
            return render(request, 'register/profile.html', context)
        else:
            return render(request, 'register/profile.html', context)
    else:
        img_form = ProfilePictureForm()
        context = {'img_form' : img_form }
        return render(request, 'register/profile.html', context)

# function to register new company
def newCompany(request):
    if request.method == 'POST':
        form = CompanyRegistrationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            form.save()
            created = True
            form = CompanyRegistrationForm()
            context = {
                'created' : created,
                'form' : form,
                       }
            return render(request, 'register/new_company.html', context)
        else:
            return render(request, 'register/new_company.html', context)
    else:
        form = CompanyRegistrationForm()
        context = {
            'form' : form,
        }
        return render(request, 'register/new_company.html', context)

register/templates/register/login.html
<!--{% extends 'core/base.html' %}-->
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Login</li>
{% endblock breadcrumb%}

{% block body %}
<body class="app flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group">
                    <div class="card p-4">
                        <div class="card-body">
                            <form method="post" action="{% url 'core:login' %}">
                                {% csrf_token %}
                                <h1>Login</h1>
                                <p class="text-muted">Sign In to your account</p>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                    </div>
                                    <input type="text"
                                       class="form-control"
                                       name="{{ login_form.username.name }}"
                                       placeholder="{{ login_form.username.label }}"
                                       id="{{ login_form.username.id_for_label }}"
                                       {% if login_form.username.value != None %}value="{{ login_form.username.value|stringformat:'s' }}"{% endif %}
                                       maxlength="{{ login_form.username.field.max_length }}"
                                       {% if login_form.username.field.required %}required{% endif %}>
                                </div>
                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-asterisk"></i></span>
                                    </div>
                                    <input type="password"
                                       class="form-control"
                                       name="{{ login_form.password.name }}"
                                       placeholder="{{ login_form.password.label }}"
                                       id="{{ login_form.password.id_for_label }}"
                                       {% if login_form.password.value != None %}value="{{ login_form.password.value|stringformat:'s' }}"{% endif %}
                                       maxlength="{{ login_form.password.field.max_length }}"
                                       {% if login_form.password.field.required %}required{% endif %}>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-primary px-4">Login</button>
                                    </div>
                                    <div class="col-6 text-right">
                                        <button type="button" class="btn btn-link px-0">Forgot password?</button>
                                    </div>
                                    {% if login_form.errors %}
                                    <div class="alert alert-danger col-12 mt-3" role="alert">
                                        Wrong username or password
                                    </div>
                                    {% endif %}
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card text-white bg-primary py-5">
                        <div class="card-body text-center">
                            <div>
                                <h2>Sign up</h2>
                                <p class="mt-4">Register now, it's free.</p>
                                <a href="{% url 'register:new-user' %}" class="btn btn-primary active mt-3">Register Now!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

  <!-- Bootstrap and necessary plugins -->
    <script src="{% static 'core/vendors/js/jquery.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/popper.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/pace.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/Chart.min.js'%}"></script>

  <!--  main scripts -->

    <script src="{% static 'core/js/app.js'%}"></script>

  <!-- Plugins and scripts required by this views -->

  <!-- Custom scripts required by this view -->
    <script src="{% static 'core/js/main.js'%}"></script>

</body>

{% endblock %}

register/templates/register/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Friends</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12">
                    <div class="social-box" style="height:110%">
                        <div class="card">
                            <div class="card-body">
                                <img src="{{ logged_user.img.url }}" class="img-avatar m-4" alt="{{ user }}" width="20%">
                                <br>
                                <form action="" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="custom-file col-md-4">
                                        {{ img_form.img }}
                                        <label class="custom-file-label btn-sm" for="validatedCustomFile">Update picture...</label>
                                        <div>
                                            <button class="btn btn-primary btn-sm my-2" type="submit">Upload</button>
                                        </div>
                                    </div>
                                </form>
                                <ul class="mt-4">
                                    <li>
                                        <a href="{% url 'register:user'  %}?profile_id={{logged_user.id}}" class="text-dark">
                                            <strong>{{ logged_user.friends.all.count }}</strong>
                                        </a>
                                        <span>friends</span>
                                    </li>
                                    <li>
                                        <strong>{{ logged_user.user.project_set.all.count }}</strong>
                                        <span>projects</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-5">
                <div class="col-12">
                    <div class="social-box" style="">
                        <ul class="mt-3">
                            <li><span>Company: <a href="">{{ logged_user.company }}</a></span></li>
                            <li><span>Projects:
                                    {% for project in logged_user.user.project_set.all %}
                                        <a href="">{{ project.name }},</a>
                                    {% endfor %}
                                </span>
                            </li>
                        </ul>
                        <ul>
                            <li><span>Name: <a href="">{{ logged_user.user.get_full_name }}</a></span></li>
                            <li><span>e-mail: <span class="text-blue text-lowercase">{{ logged_user.user.email }}</span></span>
                            </li>
                        </ul>
                        <ul>
                            <li><span>Date joined: <span class="text-blue">{{ logged_user.user.date_joined }}</span></span></li>
                            <li><span>Last login: <span class="text-blue">{{ logged_user.user.last_login }}</span></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/user.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Friends</li>
{% endblock breadcrumb%}

{% block content %}

<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12 mb-3">
                    <div class="social-box" style="height:110%">
                        <img src="{{ user_view.img.url }}" class="img-avatar m-4" alt="{{ user_view }}" width="20%">
                        <ul>
                        <li>
                            <strong>{{ user_view.friends.all.count }}</strong>
                            <span>friends</span>
                        </li>
                        <li>
                            <strong>{{ user_view.project.all.count }}</strong>
                            <span>projects</span>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-5">
                        <div class="simple-box">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <ul class="mt-4 mx-5">
                                        <h5>Personal info:</h5>
                                        <li><span>Name:</span> {{ user_view.user.get_full_name }}</li>
                                        <li><span>Company:</span> {{ user_view.company }}</li>
                                        <li><span>E-mail:</span> {{ user_view.user.email}}</li>
                                        <li><span>Last login:</span> {{ user_view.user.last_login }}</li>
                                        <li><span>Date joined:</span> {{ user_view.user.date_joined }}</li>
                                    </ul>
                                </div>
                                <div class="col-12 col-md-6 text-left">
                                    <ul class="m-4">
                                        <h5>Tasks that {{ user_view.user.first_name }} is involved:</h5>
                                        {% for task in user_view.user.task_set.all %}
                                        <li>{{ task }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="card-body">
                                    <div class="tab-pane p-3 active show">
                                      <div class="message">
                                        <div class="py-3 pb-5 mr-3 float-left">
                                          <div class="avatar">
                                            <img src="{{ user_view.img.url }}" class="img-avatar" alt="{{ friend.user.get_full_name }}">
                                            <span class="avatar-status badge-success"></span>
                                          </div>
                                        </div>
                                        <div>
                                          <small class="text-muted">{{ user_view.user.get_full_name }}</small>
                                            {% if user_view.user.last_login %}
                                          <small class="text-muted float-right mt-1">Last login: {{ user_view.user.last_login|date:"H:i" }} in {{ user_view.user.last_login|date:"d/m" }}</small>
                                            {% endif %}
                                        </div>
                                        <div class="text-truncate font-weight-bold">{{ user_view.company }}</div>
                                        {% if user_view.user.project_set %}
                                        <em class="text-muted">Projects that {{ user_view.user.first_name }} is working:</em>
                                        <small class="text-muted">
                                            {% for project in user_view.user.project_set.all %}
                                            {{ project }},
                                            {% endfor %}
                                        </small>
                                        {% else %}
                                        <em class="text-muted">{{ user_view.user.first_name }} is working in no projects until now.</em>
                                        {% endif %}
                                      </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="card-body">
                                    <div class="tab-pane p-3 active show">
                                        {% if user_view.friends.all %}
                                        <h5 class="">{{ user_view.user.first_name }}'s Friends:</h5>
                                        <div class="row">
                                        {% for friend in user_view.friends.all %}
                                        <div class="py-3 pb-5 mr-3 float-left ml-3" style="width: 20%">
                                            <p class="avatar">
                                                <img src="{{ friend.img.url }}" class="img-avatar" alt="{{ friend.user.get_full_name }}">
                                                <span class="avatar-status badge-success"></span>
                                            </p>
                                            <p>
                                                <a href="{% url 'register:user' profile_id=friend.id%}" class="text-info">{{ friend.user.first_name }}</a>
                                            </p>
                                        </div>
                                        {% endfor%}
                                        {% else %}
                                        <em class="text-muted">{{ user_view.user.first_name }} have no friends.</em>
                                        {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

register/templates/register/users.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Users View</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
    <div class="animated fade-in">
        <div class="row">
            <table class="table table-responsive-sm table-hover table-outline mb-5 ">
                <thead class="thead-light">
                <tr>
                    <th class="text-center"><i class="fa fa-user"></i></th>
                    <th>User</th>
                    <th class="text-center">Assigned Projects</th>
                    <th>Tasks</th>
                    <th class="text-center">Assigned Tasks</th>
                    <th>Activity</th>
                </tr>
            </thead>
                    <tbody>
                        <!-- user1 -->
                        {% for user1 in users %}
                        <tr>
                            <td class="text-center">
                                <div class="avatar">
                                <img src="{{ user1.img.url }}" class="img-avatar" alt="{{ user1.email }}">
                                <span class="avatar-status badge-success"></span>
                                </div>
                            </td>
                            <td>
                                {% if user1.user.get_full_name %}
                                <div>{{ user1.user.get_full_name }}{% if user1.user.is_staff %} <span class="badge badge-pill badge-dark"> staff</span> {% endif %}</div>
                                {% else %}
                                <div>{{ user1.user.username }}{% if user1.user.is_staff %} <span class="badge badge-pill badge-dark"> staff</span> {% endif %}</div>
                                {% endif %}
                                <div class="small text-muted">
                                <span>Joined:</span> | {{ user1.user.date_joined }}
                                </div>
                            </td>
                            <td class="text-center">
                                <span class="badge badge-pill badge-dark">{{ user1.user.project_set.all.count }}</span>
                            </td>
                            <td>
                                <div class="clearfix">
                                <div class="float-left">
                                <strong>{% widthratio user1.user.task_set.values.count  tasks.count 100 %}%</strong>
                                </div>
                                <div class="float-right">
                                <small class="text-muted">of total tasks</small>
                                </div>
                                </div>
                                <div class="progress progress-xs">
                                <div class="progress-bar bg-warning" role="progressbar" style="width: {% widthratio user1.user.task_set.values.count tasks.count 100 %}%" aria-valuenow="74" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </td>
                            <td class="text-center">
                                <span class="badge badge-pill badge-dark">{{ user1.user.task_set.values.count }}</span>
                                <span class="badge badge-pill badge-dark"></span>
                            </td>
                            <td>
                                <div class="small text-muted">Last login</div>
                                <strong>{{ user1.user.last_login }}</strong>
                            </td>
                        </tr>
                        {% endfor %}
                        <!-- end user -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}